---
title: "what eko ask pan cancer"
author: "Junona Sachov"
date: "6/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load dfs}
df_BRCA_pvalue = readRDS("/Users/lunona/Desktop/BRCA/df_BRCA_pvalue.RDS")
VliveVdieVlivagen5 = readRDS("~/Desktop/BRCA/tcga_tumor_normal_datascience_proj_2022.rds")

View(VliveVdieVlivagen5)
View(df_BRCA_pvalue)

BRCAtum = VliveVdieVlivagen5$BRCA$tumor
BRCAnorm = VliveVdieVlivagen5$BRCA$normal

KIRCtum = VliveVdieVlivagen5$KIRC$tumor
KIRCnorm = VliveVdieVlivagen5$KIRC$normal

LUADtum = VliveVdieVlivagen5$LUAD$tumor
LUADnorm = VliveVdieVlivagen5$LUAD$normal

PRADtum = VliveVdieVlivagen5$PRAD$tumor
PRADnorm = VliveVdieVlivagen5$PRAD$normal

THCAtum = VliveVdieVlivagen5$THCA$tumor
THCAnorm = VliveVdieVlivagen5$THCA$normal

```

```{r compute p-values for each genes}

#Here we compute the p values of all cancer types with comparison to BRCA

pea_BRCAvsKIRC = c()
 for (i in 1:nrow(BRCAtum)){
  pea_BRCAvsKIRC[i] = wilcox.test(unlist(BRCAtum[i,]),unlist(KIRCtum[i,]),paired = FALSE )$p.value
 }
p_BRCAvsKIRC = pea_BRCAvsKIRC*length(BRCAtum[,1])


pea_BRCAvsLUAD = c()
 for (i in 1:nrow(BRCAtum)){
  pea_BRCAvsLUAD[i] = wilcox.test(unlist(BRCAtum[i,]),unlist(LUADtum[i,]),paired = FALSE )$p.value
 }
p_BRCAvsLUAD = pea_BRCAvsLUAD*length(BRCAtum[,1])


pea_BRCAvsPRAD = c()
 for (i in 1:nrow(BRCAtum)){
  pea_BRCAvsPRAD[i] = wilcox.test(unlist(BRCAtum[i,]),unlist(PRADtum[i,]),paired = FALSE )$p.value
 }
p_BRCAvsPRAD = pea_BRCAvsPRAD*length(BRCAtum[,1])


pea_BRCAvsTHCA = c()
 for (i in 1:nrow(BRCAtum)){
  pea_BRCAvsTHCA[i] = wilcox.test(unlist(BRCAtum[i,]),unlist(THCAtum[i,]),paired = FALSE )$p.value
 }
p_BRCAvsTHCA = pea_BRCAvsTHCA*length(BRCAtum[,1])

# in the end we create dataframes iwth gene names and p values for easy matching of the gene to the values in plot

df_pBRCAvsKIRC = data.frame(rownames(BRCAtum), p_BRCAvsKIRC)
df_pBRCAvsLUAD = data.frame(rownames(BRCAtum), p_BRCAvsLUAD)
df_pBRCAvsPRAD = data.frame(rownames(BRCAtum), p_BRCAvsPRAD)
df_pBRCAvsTHCA = data.frame(rownames(BRCAtum), p_BRCAvsTHCA)

```

```{r Foldchange, }

#here we find the highest and lowest P values in previous comparisons and draw out the gene
#we don't need to calculate additional correlation value because we already computed p value
#we must however also consider fold change. so we will make volcano plots for each of these comparisons
#to do this we first need to compute fold change

#each row (row not column ı checked)
#log2FC_gene1 = mean(condition1_gene) -mean(condition2_gene) @wanjun

log2FC1 = apply(BRCAtum, 1, mean) - apply(KIRCtum, 1, mean)

log2FC2 = apply(BRCAtum, 1, mean) - apply(LUADtum, 1, mean)

log2FC3 = apply(BRCAtum, 1, mean) - apply(PRADtum, 1, mean)

log2FC4 = apply(BRCAtum, 1, mean) - apply(THCAtum, 1, mean)

#PROBLEM: NaN's get produced here (PLS DEBUG)

```


```{r Vocano yea, with higher threshold }

#we make the volcano plots for all cancer types

df_volcanoplotBRCAvsKIRC = data.frame (log2FC1, p_BRCAvsKIRC)
df_volcanoplotBRCAvsKIRC$different = "NO"

df_volcanoplotBRCAvsKIRC$different[df_volcanoplotBRCAvsKIRC$log2FC1 > 0.1  &     df_volcanoplotBRCAvsKIRC$p_BRCAvsKIRC < 0.0000000000000000000001]= "UP"

df_volcanoplotBRCAvsKIRC$different[df_volcanoplotBRCAvsKIRC$log2FC1 < 0.1 &      df_volcanoplotBRCAvsKIRC$p_BRCAvsKIRC < 0.0000000000000000000001]= "DOWN"

#we plot 
library(ggplot2)
ggplot (data = df_volcanoplotBRCAvsKIRC, aes (x=log2FC1, y=-log10(p_BRCAvsKIRC), col = different)) + ggtitle("volcanoplot BRCA tumour vs KIRC tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )




df_volcanoplotBRCAvsLUAD = data.frame (log2FC2, p_BRCAvsLUAD)
df_volcanoplotBRCAvsLUAD$different = "NO"

df_volcanoplotBRCAvsLUAD$different[df_volcanoplotBRCAvsLUAD$log2FC2 > 0.1  &     df_volcanoplotBRCAvsLUAD$p_BRCAvsLUAD < 0.0000000000000000000001]= "UP"

df_volcanoplotBRCAvsLUAD$different[df_volcanoplotBRCAvsLUAD$log2FC2 < 0.1 &      df_volcanoplotBRCAvsLUAD$p_BRCAvsLUAD < 0.0000000000000000000001]= "DOWN"

#we plot

ggplot (data = df_volcanoplotBRCAvsLUAD, aes (x=log2FC2, y=-log10(p_BRCAvsLUAD), col = different)) + ggtitle("volcanoplot BRCA tumour vs LUAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )




df_volcanoplotBRCAvsPRAD = data.frame (log2FC3, p_BRCAvsPRAD)
df_volcanoplotBRCAvsPRAD$different = "NO"

df_volcanoplotBRCAvsPRAD$different[df_volcanoplotBRCAvsPRAD$log2FC3 > 0.1  &     df_volcanoplotBRCAvsPRAD$p_BRCAvsPRAD < 0.0000000000000000000001]= "UP"

df_volcanoplotBRCAvsPRAD$different[df_volcanoplotBRCAvsPRAD$log2FC3 < 0.1 &      df_volcanoplotBRCAvsPRAD$p_BRCAvsPRAD < 0.0000000000000000000001]= "DOWN"

#we plot 
library(ggplot2)
ggplot (data = df_volcanoplotBRCAvsPRAD, aes (x=log2FC3, y=-log10(p_BRCAvsPRAD), col = different)) + ggtitle("volcanoplot BRCA tumour vs PRAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )




df_volcanoplotBRCAvsTHCA = data.frame (log2FC4, p_BRCAvsTHCA)
df_volcanoplotBRCAvsTHCA$different = "NO"

df_volcanoplotBRCAvsTHCA$different[df_volcanoplotBRCAvsTHCA$log2FC4 > 0.1  &     df_volcanoplotBRCAvsTHCA$p_BRCAvsTHCA < 0.0000000000000000000001]= "UP"

df_volcanoplotBRCAvsTHCA$different[df_volcanoplotBRCAvsTHCA$flog2FC4 < 0.1 &      df_volcanoplotBRCAvsTHCA$p_BRCAvsTHCA < 0.0000000000000000000001]= "DOWN"

#we plot 
library(ggplot2)
ggplot (data = df_volcanoplotBRCAvsTHCA, aes (x=log2FC4, y=-log10(p_BRCAvsTHCA), col = different)) + ggtitle("volcanoplot BRCA tumour vs THCA tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )


```


```{r Plots (with normal grenze), }

library(ggplot2)
#Recap of all of the plots:

ggplot (data = df_volcanoplotBRCAvsKIRC, aes (x=log2FC1, y=-log10(p_BRCAvsKIRC), col = different)) + ggtitle("volcanoplot BRCA tumour vs KIRC tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )


ggplot (data = df_volcanoplotBRCAvsLUAD, aes (x=log2FC2, y=-log10(p_BRCAvsLUAD), col = different)) + ggtitle("volcanoplot BRCA tumour vs LUAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )


ggplot (data = df_volcanoplotBRCAvsPRAD, aes (x=log2FC3, y=-log10(p_BRCAvsPRAD), col = different)) + ggtitle("volcanoplot BRCA tumour vs PRAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

ggplot (data = df_volcanoplotBRCAvsTHCA, aes (x=log2FC4, y=-log10(p_BRCAvsTHCA), col = different)) + ggtitle("volcanoplot BRCA tumour vs THCA tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )


```



```{r Plots (with normal grenze and with strict), }

#Stricc Plot

#1. BRCAvsKIRC

df_volcanoplotBRCAvsKIRCstrict = data.frame (log2FC1, p_BRCAvsKIRC)
df_volcanoplotBRCAvsKIRCstrict$different = "NO"

df_volcanoplotBRCAvsKIRCstrict$different[df_volcanoplotBRCAvsKIRCstrict$log2FC1 > 0.1  &     df_volcanoplotBRCAvsKIRCstrict$p_BRCAvsKIRC < 0.0000000000000000000001]= "UP"

df_volcanoplotBRCAvsKIRCstrict$different[df_volcanoplotBRCAvsKIRCstrict$log2FC1 < 0.1 &      df_volcanoplotBRCAvsKIRCstrict$p_BRCAvsKIRC < 0.00000000000000000000001]= "DOWN"

#we plot 
library(ggplot2)
ggplot (data = df_volcanoplotBRCAvsKIRC, aes (x=log2FC1, y=-log10(p_BRCAvsKIRC), col = different)) + ggtitle("volcanoplot BRCA tumour vs KIRC tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

ggplot (data = df_volcanoplotBRCAvsKIRCstrict, aes (x=log2FC1, y=-log10(p_BRCAvsKIRC), col = different)) + ggtitle("volcanoplot BRCA tumour vs KIRC tumour STRICT") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

#As you can see in the "STRİCT" df we have only the most differentially expressed genes identified as up and down.
#we can make barplots with those later

#2. BRCAvsLUAD

df_volcanoplotBRCAvsLUADstrict = data.frame (log2FC2, p_BRCAvsLUAD)
df_volcanoplotBRCAvsLUADstrict$different = "NO"

df_volcanoplotBRCAvsLUADstrict$different[df_volcanoplotBRCAvsLUADstrict$log2FC2 > 0.1  & df_volcanoplotBRCAvsLUADstrict$p_BRCAvsLUAD < 0.000000000000001]= "UP"

df_volcanoplotBRCAvsLUADstrict$different[df_volcanoplotBRCAvsLUADstrict$log2FC2 < 0.1 & df_volcanoplotBRCAvsLUADstrict$p_BRCAvsLUAD <  0.0000000000000001]= "DOWN"


library(ggplot2)
ggplot (data = df_volcanoplotBRCAvsLUAD, aes (x=log2FC2, y=-log10(p_BRCAvsLUAD), col = different)) + ggtitle("volcanoplot BRCA tumour vs LUAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

ggplot (data = df_volcanoplotBRCAvsLUADstrict, aes (x=log2FC2, y=-log10(p_BRCAvsLUAD), col = different)) + ggtitle("volcanoplot BRCA tumour vs LUAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

#3. BRCAvsPRAD
df_volcanoplotBRCAvsPRADstrict = data.frame (log2FC3, p_BRCAvsPRAD)
df_volcanoplotBRCAvsPRADstrict$different = "NO"

df_volcanoplotBRCAvsPRADstrict$different[df_volcanoplotBRCAvsPRADstrict$log2FC3 > 0.1  & df_volcanoplotBRCAvsPRADstrict$p_BRCAvsPRAD < 0.000000000000001]= "UP"

df_volcanoplotBRCAvsPRADstrict$different[df_volcanoplotBRCAvsPRADstrict$log2FC3 < 0.1 & df_volcanoplotBRCAvsPRADstrict$p_BRCAvsPRAD <  0.0000000000000001]= "DOWN"


library(ggplot2)
ggplot (data = df_volcanoplotBRCAvsPRAD, aes (x=log2FC3, y=-log10(p_BRCAvsPRAD), col = different)) + ggtitle("volcanoplot BRCA tumour vs PRAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

ggplot (data = df_volcanoplotBRCAvsPRADstrict, aes (x=log2FC3, y=-log10(p_BRCAvsPRAD), col = different)) + ggtitle("volcanoplot BRCA tumour vs PRAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

# 4. BRCAvsTHCA

df_volcanoplotBRCAvsTHCAstrict = data.frame (log2FC4, p_BRCAvsTHCA)
df_volcanoplotBRCAvsTHCAstrict$different = "NO"

df_volcanoplotBRCAvsTHCAstrict$different[df_volcanoplotBRCAvsTHCAstrict$log2FC4 > 0.1  & df_volcanoplotBRCAvsTHCAstrict$p_BRCAvsTHCA < 0.000000000000001]= "UP"

df_volcanoplotBRCAvsTHCAstrict$different[df_volcanoplotBRCAvsTHCAstrict$log2FC4 < 0.1 & df_volcanoplotBRCAvsTHCAstrict$p_BRCAvsTHCA <  0.0000000000000001]= "DOWN"


library(ggplot2)
ggplot (data = df_volcanoplotBRCAvsTHCA, aes (x=log2FC4, y=-log10(p_BRCAvsTHCA), col = different)) + ggtitle("volcanoplot BRCA tumour vs THCA tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

ggplot (data = df_volcanoplotBRCAvsTHCAstrict, aes (x=log2FC4, y=-log10(p_BRCAvsTHCA), col = different)) + ggtitle("volcanoplot BRCA tumour vs PRAD tumour") + geom_point() + theme_minimal() + scale_color_manual(values = c ("pink","black", "lightblue"))+ theme (text=element_text(size = 8) )

```



```{r get genes, }

#1. BRCAvsKIRC

Uppers1 <- df_volcanoplotBRCAvsKIRCstrict[ which(df_volcanoplotBRCAvsKIRCstrict$different =='UP'),]
#View(Uppers) #72 genes

Downers1 <- df_volcanoplotBRCAvsKIRCstrict[ which(df_volcanoplotBRCAvsKIRCstrict$different =='DOWN'),]
#View(Downers) #65 genes

UppersExpression1 =  SkinnyBoy[(match(rownames(Uppers1), rownames(SkinnyBoy))), ]
UppersExpression1 = na.omit(UppersExpression1)

DownersExpression1 =  SkinnyBoy[(match(rownames(Downers1), rownames(SkinnyBoy))), ]
DownersExpression1 = na.omit(DownersExpression1)
View(DownersExpression1)


#2. BRCAvsLUAD

Uppers2 <- df_volcanoplotBRCAvsLUADstrict[ which(df_volcanoplotBRCAvsLUADstrict$different =='UP'),]
#View(Uppers) #72 genes

Downers2 <- df_volcanoplotBRCAvsLUADstrict[ which(df_volcanoplotBRCAvsLUADstrict$different =='DOWN'),]
#View(Downers) #65 genes

UppersExpression2 =  SkinnyBoy[(match(rownames(Uppers2), rownames(SkinnyBoy))), ]
UppersExpression2 = na.omit(UppersExpression2)

DownersExpression2 =  SkinnyBoy[(match(rownames(Downers2), rownames(SkinnyBoy))), ]
DownersExpression2 = na.omit(DownersExpression2)


#3. BRCAvsPRAD
Uppers3 <- df_volcanoplotBRCAvsPRADstrict[ which(df_volcanoplotBRCAvsPRADstrict$different =='UP'),]
#View(Uppers) #72 genes

Downers3 <- df_volcanoplotBRCAvsPRADstrict[ which(df_volcanoplotBRCAvsPRADstrict$different =='DOWN'),]
#View(Downers) #65 genes

UppersExpression3 =  SkinnyBoy[(match(rownames(Uppers3), rownames(SkinnyBoy))), ]
UppersExpression3 = na.omit(UppersExpression3)

DownersExpression3 =  SkinnyBoy[(match(rownames(Downers3), rownames(SkinnyBoy))), ]
DownersExpression3 = na.omit(DownersExpression3)


# 4. BRCAvsTHCA

Uppers4 <- df_volcanoplotBRCAvsTHCAstrict[ which(df_volcanoplotBRCAvsTHCAstrict$different =='UP'),]
#View(Uppers) #72 genes

Downers4 <- df_volcanoplotBRCAvsTHCAstrict[ which(df_volcanoplotBRCAvsTHCAstrict$different =='DOWN'),]
#View(Downers) #65 genes

UppersExpression4 =  SkinnyBoy[(match(rownames(Uppers4), rownames(SkinnyBoy))), ]
UppersExpression4 = na.omit(UppersExpression4)

View(UppersExpression4)
DownersExpression4 =  SkinnyBoy[(match(rownames(Downers4), rownames(SkinnyBoy))), ]
DownersExpression4 = na.omit(DownersExpression4)

```

```{r saving the dataframes}
library(plyr) #for function rbind.fill

UP.ind1 = cbind(UppersExpression1, "UP")#UP is very last columnUP.ind1.1 = t(UP.ind1)
View(UP.ind1) #181 
View (DOWN.ind1)#215 
DOWN.ind1 = cbind(DownersExpression1, "DOWN")
BRCAvsKIRC.df = rbind.fill(UP.ind1,  DOWN.ind1) # here ensbeml names are being omitted maybe bc they donw match betweeen up and down 


#2
UP.ind2 = cbind(UppersExpression2, "UP")
DOWN.ind2 = cbind(DownersExpression2, "DOWN")
BRCAvsLUAD.df = rbind.fill(UP.ind2,DOWN.ind2)

#3
UP.ind3 = cbind(UppersExpression3, "UP")
DOWN.ind3 = cbind(DownersExpression3, "DOWN")
BRCAvsPRAD.df = rbind.fill(UP.ind3,DOWN.ind3)

#4
UP.ind4 = cbind(UppersExpression4, "UP")
DOWN.ind4 = cbind(DownersExpression4, "DOWN")
BRCAvsTHCA.df = rbind.fill(UP.ind4,DOWN.ind4)

```

```{r saving the dataframes}
Pan_cancer_analysis.df = rbind.data.frame(BRCAvsKIRC.df, BRCAvsLUAD.df, BRCAvsPRAD.df, BRCAvsTHCA.df) # to add ensembl back maybe write for loop where in one line the expression values form the genes is matched with skinnboy and add  the ensembl id into acolumn (first one, before everything)

```

```{r putting names}
Ensembl_ID = rownames(UP.ind1)
Ensembl_ID = append(Ensembl_ID,  rownames (DOWN.ind1))
Ensembl_ID = append(Ensembl_ID,  rownames (UP.ind2))
Ensembl_ID = append(Ensembl_ID,  rownames (DOWN.ind2))
Ensembl_ID = append(Ensembl_ID,  rownames (UP.ind3))
Ensembl_ID = append(Ensembl_ID,  rownames (DOWN.ind3))
Ensembl_ID = append(Ensembl_ID,  rownames (UP.ind4))
Ensembl_ID = append(Ensembl_ID,  rownames (DOWN.ind4))


Pan_cancer_analysis_wID.df = cbind(Ensembl_ID,Pan_cancer_analysis.df)
View (Pan_cancer_analysis_wID.df)

saveRDS(Pan_cancer_analysis_wID.df, file ="/Users/lunona/Desktop/BRCA/Pan_cancer_analysis_wID.df.RDS")
```

```{r saving the 4 data frames separatly}
#1
Ensembl_ID_unq1 = rownames(UP.ind1)
Ensembl_ID_unq1 = append(Ensembl_ID_unq1,  rownames (DOWN.ind1))
BRCAvsKIRC_wID.df = cbind (Ensembl_ID_unq1,BRCAvsKIRC.df) 

#saveRDS(BRCAvsKIRC_wID.df, file ="/Users/lunona/Desktop/BRCA/BRCAvsKIRC_wID.df.RDS")

#2
Ensembl_ID_unq2 = rownames(UP.ind2)
Ensembl_ID_unq2 = append(Ensembl_ID_unq2,  rownames (DOWN.ind2))
BRCAvsLUAD_wID.df = cbind (Ensembl_ID_unq2,BRCAvsLUAD.df) 

#saveRDS(BRCAvsLUAD_wID.df, file ="/Users/lunona/Desktop/BRCA/BRCAvsLUAD_wID.df.RDS")

#3
Ensembl_ID_unq3 = rownames(UP.ind3)
Ensembl_ID_unq3 = append(Ensembl_ID_unq3,  rownames (DOWN.ind3))
BRCAvsPRAD_wID.df = cbind (Ensembl_ID_unq3,BRCAvsPRAD.df) 

#saveRDS(BRCAvsPRAD_wID.df, file ="/Users/lunona/Desktop/BRCA/BRCAvsPRAD_wID.df.RDS")

#4 

Ensembl_ID_unq4 = rownames(UP.ind4)
Ensembl_ID_unq4 = append(Ensembl_ID_unq4,  rownames (DOWN.ind4))
BRCAvsTHCA_wID.df = cbind (Ensembl_ID_unq4, BRCAvsTHCA.df) 

#saveRDS(BRCAvsTHCA_wID.df, file ="/Users/lunona/Desktop/BRCA/BRCAvsTHCA_wID.df.RDS")

```









```{r lookat corrolation, }

# do all comparisons 

#1. BRCAvsKIRC
UppersMeanExp1 = apply(UppersExpression1, 1, mean)
DownersMeanExp1 = apply(DownersExpression1, 1, mean)

UppersMeanExp2 = apply(UppersExpression2, 1, mean)
DownersMeanExp2 = apply(DownersExpression2, 1, mean)


Testpresso1 =  SkinnyBoy[(match(rownames(df_BRCA_pvalue), rownames(SkinnyBoy))), ]
Testpresso1 = na.omit(Testpresso1)


plot(UppersMeanExp1[1:100], Testpresso1[1:100], pch = 19, col = "lightblue")


View(df_BRCA_pvalue)





n = cor.test(UppersMeanExp1[1:100], UppersMeanExp1[1:100])
n$estimate

a = cor.test(UppersMeanExp1[1:100], UppersMeanExp2[1:100])
a$estimate

b = cor.test(UppersMeanExp1[1:100], DownersMeanExp1[1:100])
b$estimate


View(UppersExpression1)


#corrolation plots of first 200 upper genes in several patients
for (i in 1:10) {
  
  plot(UppersExpression1[1:200,i], UppersExpression1[1:200, i+1], pch = 19, col = "lightblue")

}

UpperGene_AllPatientsCor = c()

for (i in 1:(length(UppersExpression1[,1])-1)) {
  
  z = cor.test(UppersExpression1[,i], UppersExpression1[, i+1], pch = 19, col = "lightblue")
  UpperGene_AllPatientsCor[i] = z$estimate

}

hist(UpperGene_AllPatientsCor, breaks = 40)

```










DİAGNOSTİC TESTS
```{r compute p-values for each genes}
#DİAGNOSTİK TESTS

View(BRCAtum)
View(KIRCtum)

nrow(BRCAtum) == nrow(KIRCtum) # returns true
# patients are different but the genes are not

match(rownames(BRCAtum), rownames(KIRCtum))
#reihenfolge of the genes are also the same. we can get to work now

length(BRCAtum[1,]) == length(KIRCtum[1,]) # returns false v sad
length(BRCAtum[1,]) - length(KIRCtum[1,]) #BRCA has 39 more patients

#to run wilcox test we need the patient numbers to be same
min( length(BRCAtum[1,]), length(KIRCtum[1,]) , length(LUADtum[1,]) , length(PRADtum[1,]) , length(THCAtum[1,]) )
max( length(BRCAtum[1,]), length(KIRCtum[1,]) , length(LUADtum[1,]) , length(PRADtum[1,]) , length(THCAtum[1,]) )

#max 111 min 52. we need to exclude a lot of patients. who we gonna exclude? 
#no wait it do b working when paired = false


```