---
title: "yoyo age group"
author: "Junona Sachov"
date: "7/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#grouping age of patients into 8 groups 
library(dplyr)
library(tibble)
library(magrittr)
library(tidyr)

#     extract
df.age_umap = as.data.frame(Data$Age)

groups.age_raw_umap = group_by(.data= df.age_umap, .add = FALSE, .drop = group_by_drop_default(.data))
#group  0-30, 30-60, 60 over 
groups.age1_umap = groups.age_raw_umap %>%
  mutate(age_group=as.character(cut(Data$Age,
                  breaks=c(15, 30, 40, 50, 60, 70, 80, 90, 99, Inf),
                  labels=c("15-30","30-40","40-50","50-60", "60-70", "70-80", "80-90", "90-99", ">99")))
  ) %>% 
  group_by(Data$Age)  %>%
  ungroup()

# Convert Classes ‘tbl_df’ into dataframe 
groups.age_umap = as.data.frame(groups.age1_umap)
age_groups.l_umap= list(groups.age_umap$age_group)
view(groups.age1_umap)

umap_age.df =cbind.data.frame(Data, groups.age1_umap)
View(umap_age.df)
saveRDS(umap_age.df,  file="/Users/lunona/Desktop/umap_age.df.RDS")


#put number of patients in an age group  in vector
numberof_age_15_30_umap = aggregate(groups.age_umap$age_group == "15-30", by=age_groups.l, sum)
numberof_age_30_40_umap = aggregate(groups.age_umap$age_group == "30-40", by=age_groups.l, sum)
numberof_age_40_50_umap = aggregate(groups.age_umap$age_group == "40-50", by=age_groups.l, sum)
numberof_age_50_60_umap = aggregate(groups.age_umap$age_group == "50-60", by=age_groups.l, sum)
numberof_age_60_70_umap = aggregate(groups.age_umap$age_group == "60-70", by=age_groups.l, sum)
numberof_age_70_80_umap = aggregate(groups.age_umap$age_group == "70-80", by=age_groups.l, sum)
numberof_age_80_90_umap = aggregate(groups.age_umap$age_group == "80-90", by=age_groups.l, sum) # no patient above 90

Number_ageAnnot_umap = c (numberof_age_15_30_umap[1,2],numberof_age_30_40_umap[2,2], numberof_age_40_50_umap[3,2], numberof_age_50_60_umap[4,2], numberof_age_60_70_umap[5,2], numberof_age_70_80_umap[6,2], numberof_age_80_90_ump[7,2])


```

