# Appendix

## Plots
hello
## Code
world

```{r challenge1, eval =FALSE}
#createn einer liste mit allen patienten in dfs sortiert nach krebs
cancers = list();cancers = vector('list',length(table(tcga_anno$cancer_type_abbreviation)))
names(cancers) = names(table(tcga_anno$cancer_type_abbreviation))
i=1
for (i in 1:length(cancers)){
  cancers[[i]] = tcga_exp_cleaned[,tcga_anno$cancer_type_abbreviation == names(cancers)[i]]
}
#function die einen krebstypen df und genesets als input nimmt und ein df mit pvalues ausgibt
enrichment = function(expressiondata, genesets = genesets_ids){
  ESmatrix = sapply(genesets, FUN = function(x){
    ins = na.omit(match(x,rownames(expressiondata)))#indices der gene im aktuellen set
    outs = -ins#indices der gene nicht im aktuellen set
    #gibt einen vektor der für jeden patienten den pval für das aktuelle gene enthält
    res = NULL
    for (i in 1:ncol(expressiondata)){#testet für jeden patienten
      res[i] = wilcox.test(expressiondata[ins,i],expressiondata[outs,i],'two.sided')$p.value
    }
    return(res)
  })
  row.names(ESmatrix) = colnames(expressiondata); return(ESmatrix)
}
pvalueslist = lapply(cancers, enrichment)#für die tests für jeden krebstypen durch
```

```{r challenge2, eval=FALSE}
get_top10pathways_from_pvalues = function(df_p_values, length_genesets) {
  
  require(ggplot2)
  
  results <- list()
    
  df_p_values_log10 <- -log10(as.data.frame(df_p_values))
    
  mean_pathway <- as.data.frame(apply(df_p_values_log10, 1, mean))
  rownames(mean_pathway) <- rownames(df_p_values_log10)
  
  ordered_score <- mean_pathway[order(-mean_pathway[ ,1]), 1]
  top_10 <- data.frame(ordered_score[1:10])
  colnames(top_10) <- "mean_pathway"
  
  ordered_names <- order(-mean_pathway[ ,1])
  top_10_names <- ordered_names[1:10]
  top_10$pathway_names <- row.names(mean_pathway)[top_10_names]
  
  results[[1]] <- top_10
  
  results[[2]] <- ggplot(data = top_10, aes(x = mean_pathway, y = reorder(pathway_names, mean_pathway)))+
    geom_bar(stat = "identity")+
    coord_cartesian(xlim =c(3, 3.75))+
    labs(title = names(df_p_values),
         x = "mean p-value pathway",
         y = "pathway name")
  
  pathway_size <- order(-mean_pathway[ ,1])
  top_10_size <- pathway_size[1:10]
  top_10$pathway_size <- length_genesets[top_10_size]
  
  results[[3]] <- ggplot(data = top_10, aes(x = mean_pathway, y = reorder(pathway_names,
                                                                          mean_pathway)))+
    geom_point(aes(size = pathway_size))+
    labs(title = names(df_p_values),
         x = "mean p-value pathway",
         y = "pathway name")
  
  return(results)
}
```
