---
title: "Correlation_Analyis"
author: "linh"
date: '2022-07-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r making the correlation df for all pw}

cor_matrix = data.frame()

for (n in 1:1114) {
  for (m in 1:1114) {
    cor_matrix [n,m] = cor(pw_activity_SkinnyBRCA[n,], pw_activity_SkinnyBRCA[m,],  method = "pearson", use = "complete.obs")
  }
}

#View (cor_matrix)

#rownames(pw_activity_SkinnyBRCA)

rownames(cor_matrix) = rownames(pw_activity_SkinnyBRCA)

colnames (cor_matrix) = rownames (pw_activity_SkinnyBRCA)

```


```{r heatmap correlation}

library(pheatmap)
p = pheatmap (cor_matrix, angle_col=45, cellwidth = 0.25,main = "correlation heatmap for all pathways BRCA patients", width = 10, height = 10, fontsize = 8,  show_colnames = F, show_rownames = F, treeheight_row = F, treeheight_col = F)

View (cor_matrix)



#sherlock mode

## add metabolic / hallmark / C2
pw_name_heatmap_corr = colnames(cor_matrix[p$tree_row[["order"]],])
# creating pw_cate
pw_corr = data.frame ()

rowno = match (CPathwaysNames,pw_name_heatmap_corr)

pw_corr [na.omit (rowno),1] = "C2_curated_genes"

## hallmark 
rowno_hall = match (Hallmark_Names,pw_name_heatmap_corr)

pw_corr [na.omit (rowno_hall),1] = "Hallmark Genesets"

##Metabolic
rowno_metabolic = match (MetabolicPathwayNames,pw_name_heatmap_corr)

pw_corr [na.omit (rowno_metabolic),1] = "Metabolic Genesets"

row.names(pw_corr) = pw_name_heatmap_corr


## heatmap with annotation
p = pheatmap (cor_matrix, angle_col=45, cellwidth = 0.25,main = "correlation heatmap for all pathways BRCA patients", width = 10, height = 10, fontsize = 8,  show_colnames = F, show_rownames = F, treeheight_row = F, treeheight_col = F, annotation_col = pw_corr, annotation_row = pw_corr)


##SHERLOCK MODE: find the pathways in the cluster
hc <- p$tree_row

lbl <- cutree(hc, 4) 
# find genes corresponding to first group, ...
pathways_1stclsuter = which(lbl==1)
no_corr_pw_1 = match (names (pathways_1stclsuter), pw_name_heatmap_corr)
pathways_group1_correlation = pw_name_heatmap_corr[no_corr_pw_1]
#group 1: 743
pathways_2ndclsuter = which(lbl==2)
no_corr_pw_2 = match (names (pathways_2ndclsuter), pw_name_heatmap_corr)
pathways_group2_correlation = pw_name_heatmap_corr[no_corr_pw_2]
# group 2: 141
pathways_3rdclsuter = which(lbl==3)
no_corr_pw_3 = match (names (pathways_3rdclsuter), pw_name_heatmap_corr)
#group 3: 118
pathways_4thclsuter = which(lbl==4)
no_corr_pw_4 = match (names (pathways_4thclsuter), pw_name_heatmap_corr)
#group 4: 112

# saving groups of pathways that correlated the most with each other

saveRDS (pathways_group1_correlation, file = "C:/Users/trinh/Documents/GitHub/DATATSETS/pathways_group1_correlation.RDS")

```

