---
title: "work with msigdbr"
author: "Junona Sachov"
date: "5/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#hallmark PI3K/Akt/MTOR 
PI3K_AKT_MTOR.vec = as.vector(HALLMARK_PI3K_AKT_MTOR_SIGNALING.v7.5.1)

#HALLMARK_MYC_TARGETS_V1
HALLMARK_MYC_TARGETS_V1.vec = as.vector(HALLMARK_MYC_TARGETS_V1.v7.5.1)

#HALLMARK_MYC_TARGETS_V2
HALLMARK_MYC_TARGETS_V2.vec = as.vector(HALLMARK_MYC_TARGETS_V2.v7.5.1)

#HALLMARK_APOPTOSIS
HALLMARK_APOPTOSIS.vec = as.vector(HALLMARK_APOPTOSIS.v7.5.1)

#KEGG_GALACTOSE_METABOLISM
KEGG_GALACTOSE_METABOLISM.vec = as.vector(KEGG_GALACTOSE_METABOLISM.v7.5.1)

#KEGG_FRUCTOSE_AND_MANNOSE_METABOLISM
KEGG_FRUCTOSE_AND_MANNOSE_METABOLISM.vec = as.vector(KEGG_FRUCTOSE_AND_MANNOSE_METABOLISM.v7.5.1)

#KEGG_CITRATE_CYCLE_TCA_CYCLE
KEGG_CITRATE_CYCLE_TCA_CYCLE.vec = as.vector(KEGG_CITRATE_CYCLE_TCA_CYCLE.v7.5.1)

#BIOCARTA_KREB_PATHWAY
BIOCARTA_KREB_PATHWAY.vec = as.vector(BIOCARTA_KREB_PATHWAY.v7.5.1)

#WP_AMINO_ACID_METABOLISM (WikiPathways)
WP_AMINO_ACID_METABOLISM.vec = as.vector(WP_AMINO_ACID_METABOLISM.v7.5.1)

#WP_ESTROGEN_METABOLISM
WP_ESTROGEN_METABOLISM.vec = as.vector(WP_ESTROGEN_METABOLISM.v7.5.1)

#WP_FATTY_ACID_BETAOXIDATION
WP_FATTY_ACID_BETAOXIDATION.vec = as.vector(WP_FATTY_ACID_BETAOXIDATION.v7.5.1)

#WP_EICOSANOID_METABOLISM_VIA_LIPOOXYGENASES_LOX
WP_EICOSANOID_METABOLISM_VIA_LIPOOXYGENASES_LOX.vec = as.vector(WP_EICOSANOID_METABOLISM_VIA_LIPOOXYGENASES_LOX.v7.5.1)

#KEGG_REGULATION_OF_AUTOPHAGY
KEGG_REGULATION_OF_AUTOPHAGY.vec = as.vector(KEGG_REGULATION_OF_AUTOPHAGY.v7.5.1)

#HALLMARK_GLYCOLYSIS
HALLMARK_GLYCOLYSIS.vec = as.vector(HALLMARK_GLYCOLYSIS.v7.5.1)

# KEGG_GLYCOLYSIS_GLUCONEOGENESIS
KEGG_GLYCOLYSIS_GLUCONEOGENESIS.vec = as.vector(KEGG_GLYCOLYSIS_GLUCONEOGENESIS.v7.5.1)

#GOBP_REGULATION_OF_SREBP_SIGNALING_PATHWAY
GOBP_REGULATION_OF_SREBP_SIGNALING_PATHWAY.vec = as.vector(GOBP_REGULATION_OF_FATTY_ACID_METABOLIC_PROCESS.v7.5.1)

#GOMF_MITOGEN_ACTIVATED_PROTEIN_KINASE_BINDING
GOMF_MITOGEN_ACTIVATED_PROTEIN_KINASE_BINDING.vec = as.vector(GOMF_MITOGEN_ACTIVATED_PROTEIN_KINASE_BINDING.v7.5.1)

#BIOCARTA_RB_PATHWAY
BIOCARTA_RB_PATHWAY.vec = as.vector(BIOCARTA_RB_PATHWAY.v7.5.1)

#HALLMARK_MTORC1_SIGNALING
HALLMARK_MTORC1_SIGNALING.vec = as.vector(HALLMARK_MTORC1_SIGNALING.v7.5.1)

#KEGG_PENTOSE_PHOSPHATE_PATHWAY
KEGG_PENTOSE_PHOSPHATE_PATHWAY.vec = as.vector(KEGG_PENTOSE_PHOSPHATE_PATHWAY.v7.5.1)

#GOBP_L_SERINE_BIOSYNTHETIC_PROCESS
GOBP_L_SERINE_BIOSYNTHETIC_PROCESS.vec = as.vector(GOBP_L_SERINE_BIOSYNTHETIC_PROCESS.v7.5.1)

#GOBP_FOLIC_ACID_METABOLIC_PROCESS
GOBP_FOLIC_ACID_METABOLIC_PROCESS.vec = as.vector(GOBP_FOLIC_ACID_METABOLIC_PROCESS.v7.5.1)

#KEGG_ONE_CARBON_POOL_BY_FOLATE
KEGG_ONE_CARBON_POOL_BY_FOLATE.vec = as.vector(KEGG_ONE_CARBON_POOL_BY_FOLATE.v7.5.1)

#GOBP_PROGRAMMED_CELL_DEATH_IN_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES
GOBP_PROGRAMMED_CELL_DEATH_IN_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES.vec = as.vector(GOBP_PROGRAMMED_CELL_DEATH_IN_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES.v7.5.1)

#GOBP_PROTEIN_K63_LINKED_UBIQUITINATION
GOBP_PROTEIN_K63_LINKED_UBIQUITINATION.vec = as.vector(GOBP_PROTEIN_K63_LINKED_UBIQUITINATION.v7.5.1)

#KEGG_JAK_STAT_SIGNALING_PATHWAY
KEGG_JAK_STAT_SIGNALING_PATHWAY.vec = as.vector(KEGG_JAK_STAT_SIGNALING_PATHWAY.v7.5.1)

#KENNY_CTNNB1_TARGETS_UP
KENNY_CTNNB1_TARGETS_UP.vec = as.vector(KENNY_CTNNB1_TARGETS_UP.v7.5.1)

#WP_AMPACTIVATED_PROTEIN_KINASE_AMPK_SIGNALING
WP_AMPACTIVATED_PROTEIN_KINASE_AMPK_SIGNALING.vec = as.vector(WP_AMPACTIVATED_PROTEIN_KINASE_AMPK_SIGNALING.v7.5.1)

#GOBP_REGULATION_OF_FATTY_ACID_METABOLIC_PROCESS
GOBP_REGULATION_OF_FATTY_ACID_METABOLIC_PROCESS.vec = as.vector(GOBP_REGULATION_OF_FATTY_ACID_METABOLIC_PROCESS.v7.5.1)

#KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS
KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS.vec = as.vector(KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS.v7.5.1)

#KEGG_FATTY_ACID_METABOLISM
KEGG_FATTY_ACID_METABOLISM.vec = as.vector(KEGG_FATTY_ACID_METABOLISM.v7.5.1)

#KEGG_MAPK_SIGNALING_PATHWAY
KEGG_MAPK_SIGNALING_PATHWAY.vec = as.vector(KEGG_MAPK_SIGNALING_PATHWAY.v7.5.1)

#REACTOME_PI3K_EVENTS_IN_ERBB2_SIGNALING
REACTOME_PI3K_EVENTS_IN_ERBB2_SIGNALING.vec = as.vector(REACTOME_PI3K_EVENTS_IN_ERBB2_SIGNALING.v7.5.1)

#WP_MEVALONATE_PATHWAY
WP_MEVALONATE_PATHWAY.vec = as.vector(WP_MEVALONATE_PATHWAY.v7.5.1)

#HALLMARK_CHOLESTEROL_HOMEOSTASIS#
HALLMARK_CHOLESTEROL_HOMEOSTASIS.vec = as.vector(HALLMARK_CHOLESTEROL_HOMEOSTASIS.v7.5.1)

#GOBP_ACETYL_COA_METABOLIC_PROCESS
GOBP_ACETYL_COA_METABOLIC_PROCESS.vec = as.vector(GOBP_ACETYL_COA_METABOLIC_PROCESS.v7.5.1)

#GOBP_ASPARAGINE_METABOLIC_PROCESS
GOBP_ASPARAGINE_METABOLIC_PROCESS.vec = as.vector(GOBP_ASPARAGINE_METABOLIC_PROCESS.v7.5.1)

#GOBP_INTEGRATED_STRESS_RESPONSE_SIGNALING#
GOBP_INTEGRATED_STRESS_RESPONSE_SIGNALING.vec = as.vector(GOBP_INTEGRATED_STRESS_RESPONSE_SIGNALING.v7.5.1)

#REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES
REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES.vec = as.vector(REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES.v7.5.1)

#GOBP_GLUTAMINE_FAMILY_AMINO_ACID_METABOLIC_PROCESS
GOBP_GLUTAMINE_FAMILY_AMINO_ACID_METABOLIC_PROCESS.vec = as.vector(GOBP_GLUTAMINE_FAMILY_AMINO_ACID_METABOLIC_PROCESS.v7.5.1)

#GOBP_L_PROLINE_BIOSYNTHETIC_PROCESS
GOBP_L_PROLINE_BIOSYNTHETIC_PROCESS.vec = as.vector(GOBP_L_PROLINE_BIOSYNTHETIC_PROCESS.v7.5.1)

#KEGG_ADIPOCYTOKINE_SIGNALING_PATHWAY
KEGG_ADIPOCYTOKINE_SIGNALING_PATHWAY.vec = as.vector(KEGG_ADIPOCYTOKINE_SIGNALING_PATHWAY.v7.5.1)

#GOBP_UREA_CYCLE
GOBP_UREA_CYCLE.vec = as.vector(GOBP_UREA_CYCLE.v7.5.1)

#GOBP_CITRULLINE_METABOLIC_PROCESS
GOBP_CITRULLINE_METABOLIC_PROCESS.vec = as.vector(GOBP_CITRULLINE_METABOLIC_PROCESS.v7.5.1)

#KEGG_LYSINE_DEGRADATION
KEGG_LYSINE_DEGRADATION.vec = as.vector(KEGG_LYSINE_DEGRADATION.v7.5.1)

#	GOBP_TRYPTOPHAN_CATABOLIC_PROCESS_TO_KYNURENINE
GOBP_TRYPTOPHAN_CATABOLIC_PROCESS_TO_KYNURENINE.vec = as.vector(GOBP_TRYPTOPHAN_CATABOLIC_PROCESS_TO_KYNURENINE.v7.5.1)


## check if there is no overlap between the 46 and the new pathways 
##check if all or most of the expression values an be found for all the genses in the new pathway 
#combine this list with ensbml id for further analysis stepy
```


```{r}
lit.pathways.l = list(PI3K_AKT_MTOR.vec, HALLMARK_MYC_TARGETS_V1.vec, HALLMARK_MYC_TARGETS_V2.vec,HALLMARK_APOPTOSIS.vec,KEGG_GALACTOSE_METABOLISM.vec, KEGG_FRUCTOSE_AND_MANNOSE_METABOLISM.vec, KEGG_CITRATE_CYCLE_TCA_CYCLE.vec, BIOCARTA_KREB_PATHWAY.vec,WP_AMINO_ACID_METABOLISM.vec, WP_ESTROGEN_METABOLISM.vec, WP_FATTY_ACID_BETAOXIDATION.vec,WP_EICOSANOID_METABOLISM_VIA_LIPOOXYGENASES_LOX.vec,KEGG_REGULATION_OF_AUTOPHAGY.vec,HALLMARK_GLYCOLYSIS.vec, KEGG_GLYCOLYSIS_GLUCONEOGENESIS.vec,GOBP_REGULATION_OF_SREBP_SIGNALING_PATHWAY.vec,GOMF_MITOGEN_ACTIVATED_PROTEIN_KINASE_BINDING.vec,BIOCARTA_RB_PATHWAY.vec, HALLMARK_MTORC1_SIGNALING.vec,KEGG_PENTOSE_PHOSPHATE_PATHWAY.vec,GOBP_L_SERINE_BIOSYNTHETIC_PROCESS.vec, GOBP_FOLIC_ACID_METABOLIC_PROCESS.vec,KEGG_ONE_CARBON_POOL_BY_FOLATE.vec,GOBP_PROGRAMMED_CELL_DEATH_IN_RESPONSE_TO_REACTIVE_OXYGEN_SPECIES.vec,GOBP_PROTEIN_K63_LINKED_UBIQUITINATION.vec,KEGG_JAK_STAT_SIGNALING_PATHWAY.vec,KENNY_CTNNB1_TARGETS_UP.vec,WP_AMPACTIVATED_PROTEIN_KINASE_AMPK_SIGNALING.vec,GOBP_REGULATION_OF_FATTY_ACID_METABOLIC_PROCESS.vec, KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS.vec,KEGG_FATTY_ACID_METABOLISM.vec, KEGG_MAPK_SIGNALING_PATHWAY.vec, REACTOME_PI3K_EVENTS_IN_ERBB2_SIGNALING.vec,WP_MEVALONATE_PATHWAY.vec,HALLMARK_CHOLESTEROL_HOMEOSTASIS.vec, GOBP_ACETYL_COA_METABOLIC_PROCESS.vec, GOBP_ASPARAGINE_METABOLIC_PROCESS.vec,GOBP_INTEGRATED_STRESS_RESPONSE_SIGNALING.vec,REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES.vec, GOBP_GLUTAMINE_FAMILY_AMINO_ACID_METABOLIC_PROCESS.vec, GOBP_L_PROLINE_BIOSYNTHETIC_PROCESS.vec,KEGG_ADIPOCYTOKINE_SIGNALING_PATHWAY.vec,GOBP_UREA_CYCLE.vec,GOBP_CITRULLINE_METABOLIC_PROCESS.vec,KEGG_LYSINE_DEGRADATION.vec,GOBP_TRYPTOPHAN_CATABOLIC_PROCESS_TO_KYNURENINE.vec)
```








